[package]
name = "chat"
version = "0.1.0"
authors = ["gsmlg <me@gsmlg.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.4.6"
rustyline = "5.0.2"
